---
applications:
- name: APPNAME
  buildpacks:
    - dotnet_core_buildpack
  disk_quota: 512MB
  memory: 512MB
  instances: 1
  routes:
    - route: APPNAME.STAGINGDOMAIN
  services:
    - SERVICEINSTANCENAME
  env:
    ASPNETCORE_ENVIRONMENT: Development
    SERVICE_NAME: SERVICENAME
