---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 7

inputs:
- name: concourse-pipeline-samples
- name: version-semver

run:
  path: concourse-pipeline-samples/pipelines/azure/hybrid-scenario/tasks/load-tests
