---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: microsoft/dotnet
    tag: 2.1-sdk

inputs:
- name: eshop
- name: concourse-pipeline-samples

run:
  path: concourse-pipeline-samples/pipelines/azure/hybrid-scenario/tasks/run-tests
