---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pivotalservices/docker-concourse-cf-tools
    tag: "latest"

inputs:
- name: concourse-pipeline-samples
- name: version-semver

run:
  path: concourse-pipeline-samples/pipelines/azure/hybrid-scenario/tasks/update-routes
